# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 硬底居米的部落格 | The Blog Of Indie Jimmy
subtitle: 硬底居米 Indie Jimmy
subtitle_desc: 努力爬行的碼農...
description: 硬底居米的部落格，關於寫程式、遊戲、電影、音樂、閱讀...
keywords: ruby on rails, gamedav, game development, developer, web developer, ruby
author:
  name: Jimmy Wu
  link: https://github.com/jimmy2822
language: zh-tw
timezone: Asia/Taipei

# blog favicon 圖標 location: themes/hexo-theme-skapp/source/img
favicon_ico: /img/logo.png

# 左上角主 Logo
logo: /img/logo.png

# 文章預設封面
default_cover: /img/default_cover.jpg

# Header 背景圖
header_cover: /img/header.jpg

# 404 背景圖
# error_page_bg:

# loading 背景圖
loader_img: /img/loading.gif

# theme skapp settings
menu:
  home: /
  archive: /archives

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.raiden.me
root: /
permalink: :year/:month/:day/:title/
# permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
# category_map:
# tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-skapp

# Disqus
disqus_shortname: blog-raiden-me

# Google Analytics
google_statistic: UA-122827207-2

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:jimmy2822/blog.raiden.me.git
  branch: gh-pages
  message:

# lazy loading config
lazyload:
  enable: true
  onlypost: false

# Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

# Sitemap
sitemap:
  path: sitemap.xml
