<link rel= "stylesheet" href="/js/libs/google-code-prettify/skins/{{ theme.custom_highlight_theme }}.min.css" type="text/css">
<script src= "/js/libs/google-code-prettify/prettify.js" type = "text/javascript" ></script>
<script type= "text/javascript" >
$(document).ready(function(){
    $('pre').addClass('prettyprint linenums').attr( 'style', 'overflow:auto;');
    prettyPrint();
    });
</script>
